# Generated by Django 2.2.16 on 2020-11-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="boolean",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customtext",
            name="some_chars",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
