# Generated by Django 2.2.16 on 2020-11-19 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201118_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='boolean',
        ),
    ]
