# Generated by Django 2.2.16 on 2020-11-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_remove_customtext_boolean"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="body",
        ),
        migrations.AddField(
            model_name="homepage",
            name="body_test",
            field=models.TextField(blank=True),
        ),
    ]
