# Generated by Django 2.2.16 on 2020-11-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201119_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='title',
        ),
        migrations.AddField(
            model_name='customtext',
            name='title_346',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
